package com.codegnan.jeevanraksha.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Response DTO for a bestselling medicine ranked by units sold.
 *
 * <p>Used by: GET /api/reports/bestsellers</p>
 *
 * <p>Results are ordered by {@code totalQuantitySold} descending.</p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class BestsellerResponse {

    private Integer medicineId;
    private String medicineName;
    private String category;
    private BigDecimal price;

    /** Total number of units sold across all orders. */
    private long totalQuantitySold;

    /** Total revenue generated by this medicine (INR). */
    private BigDecimal totalRevenue;
}
